version: '3'

env:
  CONTAINER_RUNTIME: podman

tasks:
  enable-ipv6:
    cmds:
      - sudo modprobe -v ip6_tables
  create-cluster:
    deps:
      - enable-ipv6
    cmds:
      - kind create cluster --name llm --config cluster.yaml
  slides:
    cmds:
      - $CONTAINER_RUNTIME run --name llm-slides -v $(pwd):/usr/share/nginx/html:ro -d -p 8080:80 nginx
  docker-clean:
    cmds:
      - $CONTAINER_RUNTIME rm -f llm-slides
